//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hasta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hasta()
        {
            this.HastaProtokol = new HashSet<HastaProtokol>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<System.DateTime> dogumtarihi { get; set; }
        public Nullable<byte> cinsiyet { get; set; }
        public Nullable<int> tc { get; set; }
        public string state { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HastaProtokol> HastaProtokol { get; set; }
    }
}
