//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class HastaProtokol
    {
        public int Id { get; set; }
        public Nullable<int> HastaId { get; set; }
        public Nullable<int> BolumId { get; set; }
        public Nullable<int> DoktorId { get; set; }
        public Nullable<System.DateTime> AcilisTarihi { get; set; }
    
        public virtual Hasta Hasta { get; set; }
    }
}
