//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IKPersonel
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<int> BolumId { get; set; }
    
        public virtual OrtakBolum OrtakBolum { get; set; }
    }
}
